const products = [
  {
    id: 1,
    name: "Chocolate Cake",
    price: 250,
    category: "cake",
    image: "Images/cake.jpg",
  },
  {
    id: 2,
    name: "Vanilla Cupcake",
    price: 90,
    category: "cake",
    image: "Images/vcupcake.jpg",
  },
  {
    id: 3,
    name: "RedVelvet Cupcake",
    price: 290,
    category: "cake",
    image: "Images/redcake.jpg",
  },
  {
    id: 4,
    name: "Pineapple Cupcake",
    price: 250,
    category: "cake",
    image: "Images/pcake.jpg",
  },
  {
    id: 5,
    name: "Croissant",
    price: 60,
    category: "pastry",
    image: "Images/croissant.jpg",
  },
  {
    id: 6,
    name: "Cinnamon Roll",
    price: 80,
    category: "pastry",
    image: "Images/croll.jpg",
  },
  {
    id: 7,
    name: "Puff",
    price: 40,
    category: "pastry",
    image: "Images/puff.jpg",
  },
  {
    id: 8,
    name: "Danish Pastry",
    price: 70,
    category: "pastry",
    image: "Images/danishpastry.jpg",
  },
  {
    id: 9,
    name: "French Baguette",
    price: 50,
    category: "bread",
    image: "Images/French_baguettes.jpg",
  },
  {
    id: 10,
    name: "Multigrain Bread",
    price: 100,
    category: "bread",
    image: "Images/mbread.jpg",
  },
   {
    id: 11,
    name: "White Bread",
    price: 100,
    category: "bread",
    image: "Images/whitebread.jpg",
  },
   {
    id: 12,
    name: "Wheat Bread",
    price: 100,
    category: "bread",
    image: "Images/wheatbread.jpg",
  }
];
